= fis-conax

This service represents the integration of the conax service, which uses Fuse Integration Service 2.0.
The integrated service is located in the repository link:https://github.com/cchet-thesis-msc/service-conax[srvice-conax].

== Local setup
The following section describe the setup of the local machine for development.

=== Windows
This section describe how to setup a windows developer machine.

* Download and install link:https://www.docker.com/docker-windows[Docker for Windows]
* Follow the instructions of the installation wizard
* Start Docker for Windows
* Open the Docker for Windows *Settings*, open tab *Daemon* and add __172.30.0.0/16__ at *insecure registries* and click *Apply* (Docker will restart)
* Download the Openshift client for Windows from the Github project link:https://github.com/Openshift/origin/releases[Openshift/origin]
* Add Openshift client location to PATH
* Install *powershift-cli* as describe at the Github project link:https://github.com/getwarped/powershift-cli[powershift-cli] (Windows wrapper util for *Openshift client*)

== How to run locally
Use the following command to build and run the service locally.

=== Preconditions
This section describes how to prepare the service project for the build and deployment.

* Set maven parameter **service.conax.basePath** to the wsdl location of the conax service. +
  E.g.: http://service-conax-myproject.10.0.75.2.nip.io

=== Build and deploy
This section describes how to build and deploy the service via the maven plugin *fabric8-maven-plugin*.

`mvn -s configuration/settings.xml -P default,fabric8 clean install spring-boot:run -DCONFIG_LOCATION_EXTERNAL=classpath:/development-application.properties`

The parameter **CONFIG_LOCATION_EXTERNAL** defines the fully qualified path to the file developer-application.properties,
which is located in `src/main/resources`.

== How to run in Openshift
This section describes how to run the service in a local Openshift cluster.

=== Preconditions
This section describes how to prepare the service project for the build and deployment.

* Set maven parameter **service.conax.basePath** to the wsdl location of the conax service. +
  E.g.: http://service-conax-myproject.10.0.75.2.nip.io/soap-api/conax?wsdl


=== Windows
This section describes how to start the local Openshift cluster on a windows machine with *powershift-cli*.

* Start Docker for Windows
* Open a Powershell
* Start the cluster with `powershift.exe cluster up [profile_name]`
* Wait until cluster is started
* Login to your Openshift project with `oc.exe login [CLUSTER_URL] -u developer -p developer`

=== Build and deploy
This section describes how to build and deploy the service via the maven plugin *fabric8-maven-plugin*.
Ensure you are logged in to your Openshift project via the CLI and that the openshift client binary location has been added to the PATH.

* `mvn -s configuration/settings.xml -P default,fabric8 clean install fabric8:deploy` +
  Deploy the service in the Openshift project
* `mvn -s configuration/settings.xml -P default,fabric8 clean compile fabric8:undeploy` +
  Undeploy the service from the Openshift project